apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: prisma
  name: prisma
spec:
  ports:
  - name: "4477"
    port: 4477
    targetPort: 4477
  selector:
    io.kompose.service: prisma
status:
  loadBalancer: {}
