apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: prisma
  name: prisma2
spec:
  ports:
  - port: 4466
    protocol: TCP
    targetPort: 4466
  selector:
    io.kompose.service: prisma
  type: NodePort
status:
  loadBalancer: {}
