apiVersion : apps/v1
kind: Deployment
metadata:
  name: "mpilinux-9e43"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "mpilinux-9e43"
  template:
    metadata:
      labels:
        app: "mpilinux-9e43"
    spec:
      containers:
        - name: "mpilinux-9e43"
          image: "mpiregistry.azurecr.io/mpilinux"
          ports:
          - containerPort: 4444