on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mpiregistry.azurecr.io
        username: ${{ secrets.acr_mpiregistry_username }}
        password: ${{ secrets.acr_mpiregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t mpiregistry.azurecr.io/mpilinux:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push mpiregistry.azurecr.io/mpilinux:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mpilinux_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep prisma | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace prisma`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: prisma
        container-registry-url: mpiregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_mpiregistry_username }}
        container-registry-password: ${{ secrets.acr_mpiregistry_password }}
        secret-name: mpilinuxdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: prisma
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mpiregistry.azurecr.io/mpilinux:${{ github.sha }}
        imagepullsecrets: |
          mpilinuxdockerauth
